# -*- coding: utf-8 -*-
"""skin_cancer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nsAKxylyrldajj_S5XousPXJR3eCZ0c6
"""

!nvidia-smi

import os
working = "/content/drive/MyDrive/yolo"

os.chdir(working)
!pwd

!pip install ultralytics==8.0.20

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

!pwd

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="ZhMKE5PkebA9PWDwPKWI")
project = rf.workspace("ayush-raj-awelj").project("skin-cancer-detection-ntfc5")
dataset = project.version(1).download("yolov8")

!yolo task=detect mode=train model=yolov8s.pt data=/content/drive/MyDrive/yolo/Skin-Cancer-Detection-1/data.yaml epochs=50 imgsz=800 plots=True



!yolo task=detect mode=val model=/content/drive/MyDrive/yolo/runs/detect/train5/weights/best.pt data=/content/drive/MyDrive/yolo/Skin-Cancer-Detection-1/data.yaml

!yolo task=detect mode=predict model=/content/drive/MyDrive/yolo/runs/detect/train5/weights/best.pt conf=0.25 source=/content/drive/MyDrive/yolo/Skin-Cancer-Detection-1/test save=True

import glob
from IPython.display import Image, display

for image_path in glob.glob(r'/content/drive/MyDrive/yolo/runs/detect/predict/*.jpg'):
      display(Image(filename=image_path, width=600))
      print("\n")

